In [1]:
# from data.loader import DataLoader
from tester import temp
import pandas as pd
import numpy as np
from typing import Dict

        start_time      open      high       low     close        volume  \
20    1.564010e+12  0.002858  0.002952  0.002848  0.002866  1.499441e+08
21    1.564100e+12  0.002866  0.002908  0.002820  0.002882  2.951775e+07
22    1.564190e+12  0.002892  0.002962  0.002750  0.002805  8.675831e+07
23    1.564270e+12  0.002794  0.002814  0.002716  0.002790  4.922512e+07
24    1.564360e+12  0.002784  0.002878  0.002758  0.002766  6.501359e+07
...            ...       ...       ...       ...       ...           ...
2100  1.743720e+12  0.162326  0.172751  0.159898  0.171249  1.132035e+09
2101  1.743810e+12  0.171249  0.171653  0.166037  0.168961  3.530294e+08
2102  1.743900e+12  0.169045  0.170108  0.145734  0.149158  1.124973e+09
2103  1.743980e+12  0.149165  0.153967  0.129746  0.149511  3.431460e+09
2104  1.744070e+12  0.149515  0.157025  0.140976  0.142169  1.470209e+09

       returns  log_returns  volatility_20d
20   -0.002957    -0.002962        0.763198
21    0.005891     0.005873        0.695537
22   -0.026984    -0.027354        0.693838
23   -0.005095    -0.005108        0.693674
24   -0.008640    -0.008678        0.693153
...        ...          ...             ...
2100  0.055571     0.054082        0.663507
2101 -0.013360    -0.013450        0.643138
2102 -0.117204    -0.124662        0.768679
2103  0.002363     0.002360        0.764117
2104 -0.049106    -0.050353        0.740181

[2085 rows x 9 columns]

/home/afiq/blogpost/umh/backtesting_framework/strategies/base.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data[f'sma_{window}'] = (
/home/afiq/blogpost/umh/backtesting_framework/strategies/base.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data[f'sma_{window}'] = (

In [2]:
temp

        start_time      open      high       low     close        volume
0     1.562280e+12  0.004499  0.004610  0.003562  0.003870  1.928298e+09
1     1.562370e+12  0.003883  0.003953  0.003367  0.003500  1.010744e+09
2     1.562460e+12  0.003505  0.003663  0.003396  0.003538  5.306140e+08
3     1.562540e+12  0.003554  0.003576  0.003400  0.003472  3.084457e+08
4     1.562630e+12  0.003479  0.003591  0.003368  0.003461  2.533756e+08
...            ...       ...       ...       ...       ...           ...
2100  1.743720e+12  0.162326  0.172751  0.159898  0.171249  1.132035e+09
2101  1.743810e+12  0.171249  0.171653  0.166037  0.168961  3.530294e+08
2102  1.743900e+12  0.169045  0.170108  0.145734  0.149158  1.124973e+09
2103  1.743980e+12  0.149165  0.153967  0.129746  0.149511  3.431460e+09
2104  1.744070e+12  0.149515  0.157025  0.140976  0.142169  1.470209e+09

[2105 rows x 6 columns]

In [3]:
from data.preprocessor import DataPreprocessor

preprocessor = DataPreprocessor()

clean_temp = preprocessor.clean_market_data(temp)

print(clean_temp)

        start_time      open      high       low     close        volume
0     1.562280e+12  0.004499  0.004610  0.003562  0.003870  1.928298e+09
1     1.562370e+12  0.003883  0.003953  0.003367  0.003500  1.010744e+09
2     1.562460e+12  0.003505  0.003663  0.003396  0.003538  5.306140e+08
3     1.562540e+12  0.003554  0.003576  0.003400  0.003472  3.084457e+08
4     1.562630e+12  0.003479  0.003591  0.003368  0.003461  2.533756e+08
...            ...       ...       ...       ...       ...           ...
2100  1.743720e+12  0.162326  0.172751  0.159898  0.171249  1.132035e+09
2101  1.743810e+12  0.171249  0.171653  0.166037  0.168961  3.530294e+08
2102  1.743900e+12  0.169045  0.170108  0.145734  0.149158  1.124973e+09
2103  1.743980e+12  0.149165  0.153967  0.129746  0.149511  3.431460e+09
2104  1.744070e+12  0.149515  0.157025  0.140976  0.142169  1.470209e+09

[2105 rows x 6 columns]

In [4]:
added_temp = preprocessor.add_returns(clean_temp)

In [5]:

from strategies import moving_average
strategy =  moving_average.MovingAverageStrategy(added_temp)

In [6]:
strategy.generate_signals()

/home/afiq/blogpost/umh/backtesting_framework/strategies/base.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data[f'sma_{window}'] = (
/home/afiq/blogpost/umh/backtesting_framework/strategies/base.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data[f'sma_{window}'] = (

In [7]:
strategy.data

,start_time,open,high,low,close,volume,returns,log_returns,volatility_20d,sma_50,sma_200
20,1.564010e+12,0.002858,0.002952,0.002848,0.002866,1.499441e+08,-0.002957,-0.002962,0.763198,NaN,NaN
21,1.564100e+12,0.002866,0.002908,0.002820,0.002882,2.951775e+07,0.005891,0.005873,0.695537,NaN,NaN
22,1.564190e+12,0.002892,0.002962,0.002750,0.002805,8.675831e+07,-0.026984,-0.027354,0.693838,NaN,NaN
23,1.564270e+12,0.002794,0.002814,0.002716,0.002790,4.922512e+07,-0.005095,-0.005108,0.693674,NaN,NaN
24,1.564360e+12,0.002784,0.002878,0.002758,0.002766,6.501359e+07,-0.008640,-0.008678,0.693153,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2100,1.743720e+12,0.162326,0.172751,0.159898,0.171249,1.132035e+09,0.055571,0.054082,0.663507,0.197774,0.255861
2101,1.743810e+12,0.171249,0.171653,0.166037,0.168961,3.530294e+08,-0.013360,-0.013450,0.643138,0.195716,0.256201
2102,1.743900e+12,0.169045,0.170108,0.145734,0.149158,1.124973e+09,-0.117204,-0.124662,0.768679,0.193263,0.256427
2103,1.743980e+12,0.149165,0.153967,0.129746,0.149511,3.431460e+09,0.002363,0.002360,0.764117,0.190938,0.256650
2104,1.744070e+12,0.149515,0.157025,0.140976,0.142169,1.470209e+09,-0.049106,-0.050353,0.740181,0.188617,0.256833

In [8]:
from main import VectorBacktester
backtester = VectorBacktester(strategy)

In [ ]:
backtester.run_backtest()

In [ ]:
results = backtester.results

            equity   returns
2100  5.914156e+07 -0.055571
2101  5.993698e+07  0.013360
2102  6.739010e+07  0.117204
2103  6.723107e+07 -0.002363
2104  7.061495e+07  0.049106

In [11]:
from analysis.metrics import AdvancedAnalyzer

analysis = AdvancedAnalyzer(result)
analysis.sharpe_ratio()

TypeError: 'NoneType' object is not subscriptable

In [13]:
print(result)

None